CREATE TABLE `res_order` (
  `order_id`                bigint(20)    NOT NULL AUTO_INCREMENT COMMENT '预约单ID',
  `user_id`                 bigint(20)    NOT NULL COMMENT '预约用户ID',
  `equip_id`                bigint(20)    NOT NULL COMMENT '设备ID',
  `quantity`                int(11)       NOT NULL DEFAULT 1 COMMENT '预约数量',
  `real_name`               varchar(30)   DEFAULT '' COMMENT '预约人姓名',
  `student_no`              varchar(30)   DEFAULT '' COMMENT '学号',
  `grade`                   varchar(20)   DEFAULT '' COMMENT '年级',
  `major`                   varchar(50)   DEFAULT '' COMMENT '专业',
  `phone`                   varchar(20)   DEFAULT '' COMMENT '手机号',
  `reserve_time`            datetime      NOT NULL COMMENT '预约开始时间',
  `expect_return_time`      datetime      NOT NULL COMMENT '预计归还时间',
  `actual_return_time`      datetime      DEFAULT NULL COMMENT '实际归还时间',
  `order_status`            char(2)       DEFAULT '0' COMMENT '预约状态（0待审批 1审批通过/使用中 2审批拒绝 3已归还 4已逾期 5已取消）',
  `reject_reason`           varchar(255)  DEFAULT '' COMMENT '拒绝理由',
  `pickup_location`         varchar(200)  DEFAULT '' COMMENT '领取地点',
  `pickup_time`             datetime      DEFAULT NULL COMMENT '领取时间（审批通过时填入）',
  `extend_status`           char(1)       DEFAULT '0' COMMENT '延期状态（0未申请 1延期审批中 2延期通过 3延期拒绝）',
  `extend_expect_return_time` datetime    DEFAULT NULL COMMENT '延期后的预计归还时间',
  `extend_reason`           varchar(255)  DEFAULT '' COMMENT '延期原因/审批意见',
  `create_by`               varchar(64)   DEFAULT '' COMMENT '创建者',
  `create_time`             datetime      DEFAULT NULL COMMENT '创建时间',
  `update_by`               varchar(64)   DEFAULT '' COMMENT '更新者',
  `update_time`             datetime      DEFAULT NULL COMMENT '更新时间',
  `remark`                  varchar(500)  DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`order_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_equip_id` (`equip_id`),
  KEY `idx_order_status` (`order_status`),
  KEY `idx_reserve_time` (`reserve_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='设备预约单表';